spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: chat
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/chatApp"
  mail:
    host: mail.inbox.lv
    port: 587
    username: jd2_chat@mail.lv
    password: UJb!zTcU21
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8080
jwt:
  secret: 6013fba8-50ec-4830-a6b6-1c2b7ef27b3a
  expiration: 3600000
#logging:
#  level:
#    root: debug